name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ${{ github.actor_id != github.repository_owner_id && 'required-approval' || '' }}
    permissions:
      contents: read
      packages: read
      id-token: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        with:
          repositories: ${{ vars.REPOSITORY }}

      - name: Verify
        env:
          REPOSITORY: ${{ vars.REPOSITORY }}
          GH_TOKEN: ${{ steps.exercise.outputs.token }}
        run: |
          set -x
          result="$(gh api \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${GITHUB_REPOSITORY_OWNER}/${REPOSITORY}/readme" \
            --jq '.name')"
          test "${result}" = "README.md"

      - name: Teardown
        if: ${{ always() }}
        uses: tmknom/revoke-github-token-action@3ab58f0a8cc1f0911d071e243343bc0a003d0d1b # v0.1.0
        with:
          token: ${{ steps.exercise.outputs.token }}
