name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      packages: read
      id-token: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        with:
          repositories: ${{ vars.REPOSITORY }}

      - name: Verify
        env:
          REPOSITORY: ${{ vars.REPOSITORY }}
          GH_TOKEN: ${{ steps.exercise.outputs.token }}
        run: |
          set -x
          result="$(gh api \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${GITHUB_REPOSITORY_OWNER}/${REPOSITORY}/readme" \
            --jq '.name')"
          test "${result}" = "README.md"

      - name: Teardown
        if: ${{ always() }}
        env:
          GH_TOKEN: ${{ steps.exercise.outputs.token }}
        run: |
          curl --location --silent --request DELETE \
            --url "${GITHUB_API_URL}/installation/token" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Authorization: Bearer ${GH_TOKEN}"
